// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  birdwatchingSidebar: [{type: 'autogenerated', dirName: 'birdwatching'}],
  gamingSidebar: [{type: 'autogenerated', dirName: 'gaming'}],
  // algorithmsSidebar: [{type: 'autogenerated', dirName: 'algorithms'}],
  algorithmsSidebar: [
    {
      type: 'category',
      label: 'Data Structures and Algorithms',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'algorithms/intro'
      },
      items: [
        'algorithms/array/array',
        'algorithms/binary-tree/binary-tree',
        'algorithms/graph/graph',
        'algorithms/hashmap/hashmap',
        'algorithms/linked-list/linked-list',
        'algorithms/queue/queue',
        'algorithms/stack/stack',
        'algorithms/string/string',
        'algorithms/trie/trie',
        'algorithms/backtracking/backtracking',
        'algorithms/binary-search/binary-search',
        'algorithms/bit/bit',
        'algorithms/design/design',
        'algorithms/dp/dp',
        'algorithms/greedy/greedy',
        'algorithms/intervals/intervals',
        'algorithms/math/math',
      ],
    },
  ],
  // algorithmsSidebar: [
  //     'algorithms/intro',
  //     'algorithms/dsa/array/array',
  //     'algorithms/dsa/binary-tree/binary-tree',
  //     'algorithms/dsa/graph/graph',
  //     'algorithms/dsa/hashmap/hashmap',
  //     'algorithms/dsa/linked-list/linked-list',
  //     'algorithms/dsa/queue/queue',
  //     'algorithms/dsa/stack/stack',
  //     'algorithms/dsa/string/string',
  //     'algorithms/dsa/trie/trie',
  //     'algorithms/dsa/backtracking/backtracking',
  //     'algorithms/dsa/binary-search/binary-search',
  //     'algorithms/dsa/bit/bit',
  //     'algorithms/dsa/design/design',
  //     'algorithms/dsa/dp/dp',
  // ],
  taigiSidebar: [{type: 'autogenerated', dirName: 'taigi'}],

  // But you can create a sidebar manually
  /*
  birdwatchingSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
