// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  birdwatchingSidebar: [
    {
      type: 'autogenerated',
      dirName: 'birdwatching',
    }
  ],
  gamingSidebar: [
    {
      type: 'autogenerated',
      dirName: 'gaming'
    }
  ],
  ebirdSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ebird'
    }
  ],
  tsiauaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'birdtaigi',
    },
  ],
  algorithmsSidebar: [
    {
      type: 'category',
      label: 'Data Structures and Algorithms',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'algorithms/intro'
      },
      items: [
        {
          type: 'category',
          label: 'Core Topics',
          collapsible: true,
          collapsed: false,
          items: [
            'algorithms/core/array/array',
            'algorithms/core/binary-tree/binary-tree',
            'algorithms/core/hashmap/hashmap',
            'algorithms/core/linked-list/linked-list',
            'algorithms/core/queue/queue',
            'algorithms/core/stack/stack',
            'algorithms/core/string/string',
            'algorithms/core/trie/trie',
          ],
        },
        {
          type: 'category',
          label: 'Advanced Topics',
          collapsible: true,
          collapsed: false,
          items: [
            'algorithms/advanced/backtracking/backtracking',
            'algorithms/advanced/binary-search/binary-search',
            'algorithms/advanced/bit/bit',
            'algorithms/advanced/design/design',
            'algorithms/advanced/dp/dp',
            'algorithms/advanced/graph/graph',
            'algorithms/advanced/greedy/greedy',
            'algorithms/advanced/intervals/intervals',
            'algorithms/advanced/math/math',
            'algorithms/advanced/matrix/matrix',
            'algorithms/advanced/prefix-sum/prefix-sum',
            'algorithms/advanced/sliding-window/sliding-window',
            'algorithms/advanced/sorting/sorting',
            'algorithms/advanced/two-pointers/two-pointers',
          ],
        },
        {
          type: 'category',
          label: 'Resources',
          collapsible: true,
          collapsed: false,
          items: [
            'algorithms/resources/basic',
            'algorithms/resources/bit',
            'algorithms/resources/sql',
          ],
        },
      ],
    },
  ],
  // algorithmsSidebar: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'algorithms'
  //   }
  // ],
  taigiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'taigi'
    }
  ],
  engineeringSidebar: [
    {
      type: 'autogenerated',
      dirName: 'engineering'
    }
    ],
};

export default sidebars;
